services:
  node-jre-app:
    build:
      context: .  # Builds from the current directory where Dockerfile is located
      dockerfile: Dockerfile
      args:
        LANGRAPH4J_GEN: generator-1.6-SNAPSHOT-jar-with-dependencies.jar  # Pass the value here
      platforms: # Specify desired platforms
        - "linux/amd64"
        - "linux/arm64"
    image: bsorrentino/langgraph4j-builder:1.6-SNAPSHOT
    container_name: langgraph4j-builder-app
    ports:
      - "3000:3000"  # Change this if your Node app uses a different port
    volumes:
      - .:/app/workspace  # Optional: Mount local directory (useful for development)
    environment:
      - NODE_ENV=production
      - LANGRAPH4J_GEN=generator-1.6-SNAPSHOT-jar-with-dependencies.jar
      - RUNNING_IN_DOCKER=true